<?php

return array(
    "Punjab" => [
        "Ahmadpur East",
        "Ahmed Nager Chatha",
        "Ali Khan Abad",
        "Alipur",
        "Arifwala",
        "Attock",
        "Bhera",
        "Bhalwal",
        "Bahawalnagar",
        "Bahawalpur",
        "Bhakkar",
        "Burewala",
        "Chillianwala",
        "Chakwal",
        "Chichawatni",
        "Chiniot",
        "Chishtian",
        "Daska",
        "Darya Khan",
        "Dera Ghazi Khan",
        "Dhaular",
        "Dina",
        "Dinga",
        "Dhudial Chakwal",
        "Dipalpur",
        "Faisalabad",
        "Ferozewala",
        "Fateh Jang",
        "Ghakhar Mandi",
        "Gojra",
        "Gujranwala",
        "Gujrat",
        "Gujar Khan",
        "Haroonabad",
        "Hasilpur",
        "Haveli Lakha",
        "Jalalpur Jattan",
        "Jampur",
        "Jaranwala",
        "Jhang",
        "Jhelum",
        "Kalabagh",
        "Karor Lal Esan",
        "Kasur",
        "Kamalia",
        "Kamoke",
        "Khanewal",
        "Khanpur",
        "Kharian",
        "Khushab",
        "Kot Adu",
        "Jauharabad",
        "Lahore",
        "Lalamusa",
        "Layyah",
        "Liaquat Pur",
        "Lodhran",
        "Malakwal",
        "Mamoori",
        "Mailsi",
        "Mandi Bahauddin",
        "Mian Channu",
        "Mianwali",
        "Multan",
        "Murree",
        "Muridke",
        "Mianwali Bangla",
        "Muzaffargarh",
        "Narowal",
        "Nankana Sahib",
        "Okara",
        "Renala Khurd",
        "Pakpattan",
        "Pattoki",
        "Pindi Bhattian",
        "Pind Dadan Khan",
        "Pir Mahal",
        "Qaimpur",
        "Qila Didar Singh",
        "Rabwah",
        "Raiwind",
        "Rajanpur",
        "Rahim Yar Khan",
        "Rawalpindi",
        "Sadiqabad",
        "Safdarabad",
        "Sahiwal",
        "Sangla Hill",
        "Sarai Alamgir",
        "Sargodha",
        "Shakargarh",
        "Sheikhupura",
        "Shujaabad",
        "Sialkot",
        "Sohawa",
        "Soianwala",
        "Siranwali",
        "Tandlianwala",
        "Talagang",
        "Taxila",
        "Toba Tek Singh",
        "Vehari",
        "Wah Cantonment",
        "Wazirabad",
        "Yazman",
        "Zafarwal",
    ],
    "Sindh" => array("Karachi", "Hyderabad", "Sukkur", "Larkana", "Mirpurkhas", "Nawabshah", "Jacobabad", "Khairpur", "Dadu", "Shikarpur", "Tando Adam", "Sanghar", "Ghotki", "Badin", "Thatta", "Matiari", "Umerkot", "Kamber Shahdadkot", "Kandhkot", "Ratodero"),
    "Khyber Pakhtunkhwa" => array("Peshawar", "Abbottabad", "Mardan", "Swat", "Nowshera", "Charsadda", "Haripur", "Kohat", "Mansehra", "Dera Ismail Khan", "Chitral", "Bannu", "Tank", "Batagram", "Hangu", "Upper Dir", "Lower Dir", "Shangla", "Karak", "Malakand"),
    "Balochistan" => array("Quetta", "Gwadar", "Sibi", "Zhob", "Turbat", "Chaman", "Loralai", "Khuzdar", "Dera Bugti", "Hub", "Nushki", "Kharan", "Lasbela", "Mastung", "Kech", "Awaran", "Barkhan", "Killa Saifullah", "Jhal Magsi", "Kalat"),
    "Gilgit-Baltistan" => array("Gilgit", "Skardu", "Chilas", "Ghanche", "Astore", "Hunza", "Nagar", "Shigar", "Khaplu", "Diamer", "Ghizer", "Shimshal", "Kharmang", "Rondo", "Darel", "Tangir", "Naltar", "Sherqilla", "Tolti", "Kargah"),
    "Azad Kashmir" => array("Muzaffarabad", "Mirpur", "Kotli", "Bhimber", "Rawalakot", "Bagh", "Haveli", "Hattian", "Neelum Valley", "Poonch", "Sudhanoti", "Leepa", "Kail", "Kotla", "Mang", "Barnala", "Lasdana", "Tatta Pani", "Charoi", "Sarla")
);
